pawel_wiki_homepage:
    path:     /hello/{name}
    defaults: { _controller: PawelWikiBundle:Default:index }

pawel_wiki_db_test:
    path:     /artykul/{tytul}
    defaults: { _controller: PawelWikiBundle:WyswietlStrone:WyswietlStrone }