pawel_wiki_homepage:
    path:     /hello/{name}
    defaults: { _controller: PawelWikiBundle:Default:index }

pawel_wiki_db_test:
    path:     /strona/{tytul}
    defaults: { _controller: PawelWikiBundle:WyswietlStrone:WyswietlStrone }

pawel_wiki_artykul:
    path:     /artykul/{tytul}
    defaults: { _controller: PawelWikiBundle:WyswietlArtykul:WyswietlArtykul }

pawel_wiki_nowy_artykul:
    path:     /nowy_artykul
    defaults: { _controller: PawelWikiBundle:WyswietlArtykul:NowyArtykul }

pawel_wiki_skasuj_artykul:
    path:     /skasuj/{tytul}
    defaults: { _controller: PawelWikiBundle:WyswietlArtykul:SkasujArtykul }

pawel_wiki_edytuj_artykul:
    path:     /edytuj/{tytul}
    defaults: { _controller: PawelWikiBundle:WyswietlArtykul:edytujArtykul }