pawel_wiki_homepage:
    path:     /hello/{name}
    defaults: { _controller: PawelWikiBundle:Default:index }

pawel_wiki_db_test:
    path:     /strona/{tytul}
    defaults: { _controller: PawelWikiBundle:WyswietlStrone:WyswietlStrone }

pawel_wiki_artykul_test:
    path:     /artykul/{tytul}
    defaults: { _controller: PawelWikiBundle:WyswietlArtykul:WyswietlArtykul }

pawel_wiki_nowy_artykul:
    path:     /nowy_artykul
    defaults: { _controller: PawelWikiBundle:NowyArtykul:NowyArtykul }    