pawel_wiki_strona_glowna:
    path:     /index
    defaults: { _controller: PawelWikiBundle:StronaGlowna:StronaGlowna }

pawel_wiki_strona:
    path:     /strona/{tytul}
    defaults: { _controller: PawelWikiBundle:WyswietlStrone:WyswietlStrone }

pawel_wiki_artykul:
    path:     /artykul/{tytul}
    defaults: { _controller: PawelWikiBundle:WyswietlArtykul:WyswietlArtykul }

pawel_wiki_nowy_artykul:
    path:     /nowy_artykul
    defaults: { _controller: PawelWikiBundle:WyswietlStrone:NowyArtykul }

pawel_wiki_edytuj_artykul:
    path:     /edytuj/{tytul}
    defaults: { _controller: PawelWikiBundle:WyswietlStrone:edytujArtykul }

pawel_wiki_skasuj_artykul:
    path:     /skasuj/{tytul}
    defaults: { _controller: PawelWikiBundle:WyswietlArtykul:SkasujArtykul }